[package]
name = "web-console-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
once_cell = "1.8.0"
sailfish = "0.3.3"
